In [48]:
cd /content/drive/MyDrive/pytorch_practice

/content/drive/MyDrive/pytorch_practice


In [49]:
!git config --global user.email 'ryuzho@github.com'
!git config --global user.name 'ryuzho'

In [ ]:
!git add .
!git status
!git commit -m 'tensor'
!git push

In [1]:
import torch
import numpy as np

In [2]:
torch.__version__

'1.11.0+cu113'

In [6]:
x_data = torch.tensor([1,2,3,4])
x = torch.rand_like(x_data, dtype=torch.float)
print(x)

tensor([0.6397, 0.4162, 0.6909, 0.1219])


In [11]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
rand_tensor.device

device(type='cpu')

In [14]:
tensor = torch.tensor([1,2,3,4])
print(tensor.device)
if torch.cuda.is_available():
  tensor = tensor.to("cuda")
print(tensor.device)

cpu
cuda:0


In [18]:
tensor = torch.rand(3,3)
print(tensor)
print(tensor[...,-1])


tensor([[0.1905, 0.9865, 0.0020],
        [0.0493, 0.9055, 0.1294],
        [0.8173, 0.2550, 0.0094]])
tensor([0.0020, 0.1294, 0.0094])


In [29]:
tensor = torch.tensor([[1,2],[3,4]])
y1 = tensor@tensor.T
y2 = tensor.matmul(tensor.T)
type(y2.sum().item())

int

In [33]:
print(tensor.add(5))
print(tensor)
print(tensor.add_(5))
print(tensor)
# memory 일부 절약 but 기록(history)가 즉시 삭제되어 derivative 계산에 문제 발생 가능, 사용을 권장하지 않음

tensor([[6, 7],
        [8, 9]])
tensor([[1, 2],
        [3, 4]])
tensor([[6, 7],
        [8, 9]])
tensor([[6, 7],
        [8, 9]])


In [34]:
t = torch.ones(5)
print(f"t : {t}")
n = t.numpy()
print(f"n : {n}")

t : tensor([1., 1., 1., 1., 1.])
n : [1. 1. 1. 1. 1.]


In [36]:
t.add_(2)
print(t)
print(n)
# CPU상의 tensor와 numpy배열은 메모리 공간을 공유

tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


In [41]:
n = np.ones(5)
t = torch.from_numpy(n)
np.add(n,1,out=n)
print(n)
print(t)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
